import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'
import LoginBtn from './LoginBtn'
import LogoutBtn from './LogoutBtn'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/pages/api/auth/[...nextauth]'
import { cookies } from 'next/headers'
import DarkMode from './DarkMode'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  let session = await getServerSession(authOptions);
  // console.log(session);

  let darkMode = cookies().get('mode');

  return (
    <html>
      <body className={ darkMode != undefined && darkMode.value == 'dark' ? "dark-mode" : "" }>
        <div className="navbar">
          <Link href="/" className="logo">Appleforum</Link>
          <Link href="/list">List</Link>
          
          {
            session ?
            <span>{session?.user?.name} <LogoutBtn></LogoutBtn></span>
            :
            <LoginBtn></LoginBtn>
          }
          <DarkMode></DarkMode>
        </div>  
        {children}
      </body>
    </html>
  )
}
